FOR /F "tokens=* delims=" %%x in ('call ini.bat /i hex /s TerminalColor config\settings.ini') do set color=%%x
set "WHITE=[37m"
set "Black=[30m"
set "Dark_Blue=[34m"
set "Green=[32m"
set "YELLOW=[33m"
set "Cyan=[36m"
set "Red=[31m"
set "Purple=[35m"
set "Dark_Purple=[38;5;57m"
set "Orange=[33m"
set "White=[37m"
set "Grey=[90m"
set "Bright_Blue=[94m"
set "Bright_Green=[92m"
set "Bright_Cyan=[96m"
set "Bright_Red=[91m"
set "Bright_Purple=[95m"
set "Bright_Yellow=[93m"
set "Bright_White=[97m"
if %color%==07 set "RESET=[0m"
if %color%==0f set "RESET=[97m"
goto :EOF